pull_request_rules:
  - name: Automatically merge Arnaud's pull requests on green
    conditions:
      - "status-success=Test"
      - "author=aspiwack"
      - "base=master"
    actions:
      merge:
        method: merge
        strict: smart
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
