name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: aspiwack
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: build dependencies
      run: nix -L develop --command echo '=== Installed ==='
    - name: build
      run: nix -L develop --command dune build
