name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    env:
      NIXSHELL: nix-shell --pure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: aspiwack
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: build dependencies
      run: $NIXSHELL --run "echo '=== Installed ==='"
    - name: build
      run: $NIXSHELL --run "dune build"
